### ISSUE TITLE
performance difference between paper and released code/weights

### ISSUE THREAD

**Issue by jayleicn** [UKPLab/MMT-Retrieval#2]
Hi Gregor,

It seems the released weights cannot reproduce the results in the paper. I summarize the results from my local evaluation runs below (I show `Image retrieval` only):

1. using `eval_embedding.yaml` 

|                          | coco (5k) |      |      | flickr  (1k) |      |      |
|--------------------------|-----------|------|------|--------------|------|------|
|                          | R1        | R5   | R10  | R1           | R5   | R10  |
| paper (JOIN+EMB^{OSCAR}) | 52.5      | 80.0 | 88.0 | 71.6         | 91.5 | 95.0 |
| local eval               | 49.9      | 77.7 | 86.0 | 69.3         | 89.9 | 93.6 |

The released embedding model weights seems to be not the correct one? as it has a ~2% gap on image retrieval R1.

2. using `eval_joint_retrieve_rerank.yaml`

|                          | coco (5k) |      |      | flickr  (1k) |      |      |
|--------------------------|-----------|------|------|--------------|------|------|
|                          | R1        | R5   | R10  | R1           | R5   | R10  |
| paper (JOIN+CO^{OSCAR}) | 54.7      | 81.3 | 88.9 | 76.54        | 93.6 | 96.2 |
| local eval               | 10.3     | 41.3 | 67.2 | 8.5         | 27.8 | 42.6 |

The cross-encoder evaluation seems to be wrong? The results are extremely low.

3. using `eval_cross_encoder.yaml`

|                          | flickr  (1k) |      |      |
|--------------------------|--------------|------|------|
|                          | R1           | R5   | R10  |
| paper (JOIN+CE^{OSCAR}) | 76.5        | 93.4 | 96.3 |
| local eval               | 7.6         | 21.3 | 27.3 |

The `models` used in the evaluations are from https://github.com/UKPLab/MMT-Retrieval#readme:
- flickr: https://public.ukp.informatik.tu-darmstadt.de/reimers/mmt-retrieval/models/v1/oscar_join_flickr30k.zip
- coco: https://public.ukp.informatik.tu-darmstadt.de/reimers/mmt-retrieval/models/v1/oscar_join_mscoco.zip

The `features` used are all downloaded following the instructions at https://github.com/UKPLab/MMT-Retrieval/blob/master/examples/experiments/README.md#using-our-image-text-retrieval-training--evaluation-setup, e.g., the coco features and annotations are download from https://biglmdiag.blob.core.windows.net/oscar/datasets/coco_ir.zip as stated in https://github.com/microsoft/Oscar/blob/master/DOWNLOAD.md#datasets

The `python packages` used are: [my_requirements.txt](https://github.com/UKPLab/MMT-Retrieval/files/6820517/my_requirements.txt)

Here is a log for running the eval on flickr using `eval_embedding.yaml`: 
[eval_flickr_emb.log](https://github.com/UKPLab/MMT-Retrieval/files/6820525/eval_flickr_emb.log). As shown in this file, I did not change any thing except the paths.

Could you help investigate where the evaluation goes wrong?

Best,
Jie

**Comment by Aaronsom** [comment]
At first glance, your setup looks correct. I will investigate this.

**Comment by Aaronsom** [comment]
I have reproduced your results for embeddings & retrieve-rerank on Flickr30k.

Now let's see what causes this.

**Comment by Aaronsom** [comment]
So there were two problems, actually.

For embeddings, there was an additional flag in the tokenizer which slightly changed the input features for some texts which caused the slight decrease you noticed. Thank you for pointing this out! 
I will release a patch today which fixes the problem. Afterward, you should get the same results.

For the joint similarity, the weights of the classification head were set wrong when we converted a research model to the current model setup. This has been fixed (I hope) and the correct weights will be soon available.

Also, for retrieve&rerank, in the config, the value for k is 20, in the paper table, we use 10. So there are small differences there. See Table 8 in the appendix for more info.

I will update you when the patch & new weights are out. Hopefully, everything will work then as expected but if not, please feel free to write again.

**Comment by Aaronsom** [comment]
Version 0.1.1 with the patch is released and the weights have been replaced. Hope this resolves the issue.
Good luck with your endeavors!

**Comment by jayleicn** [comment]
Thank you Gregor! I have verified the reproducibility of the results. Great work!
