### ISSUE TITLE
Latest versions of sentence-transformers cause failure

### ISSUE THREAD

**Issue by berknology** [UKPLab/MMT-Retrieval#4]
Solution: Downgrade sentence-transformers to 0.4.1
![image](https://user-images.githubusercontent.com/65133028/142717622-3ab62899-d918-4bd8-bc25-b0d20da2b968.png)

**Comment by gregor-ge** [comment]
Hi,

thanks for pointing that out. sentence-transformer in 2.0.0 introduced breaking changes for us for downloading a model. Any older version should still work.
I updated the requirements.
