### ISSUE TITLE
Flickr30k dataset features cannot be downloaded because the download link has expired

### ISSUE THREAD

**Issue by luoyetingqiu** [UKPLab/MMT-Retrieval#5]
Flickr30k dataset features cannot be downloaded because the download link has expired

**Comment by gregor-ge** [comment]
Thanks for pointing that out. The original script (https://github.com/jnhwkim/ban-vqa/blob/master/tools/download_flickr.sh) now gives a new link but that uses a different format. Instead, I uploaded the features [here](https://public.ukp.informatik.tu-darmstadt.de/geigle/mmt-retrieval/flickr30k_features.zip) and updated links in the documentation.
